tower-rs/tower-grpc

tower-grpc-build/src/lib.rs

Allow influencing the way proto buffers are compiled.
Or is it better to start with default new and then provide access to mutable prost config inside?
I guess something like this is already planned, but I might want to play with it, so I decided to just write it instead of waiting. I hope it isn't too early for pull requests 😇.

Allow using non-default prost config

---

Cargo.toml
tower-grpc-examples/Cargo.toml

I've encountered a couple of dependency conflicts trying to build the `tower-grpc-examples` crate against the latest master. First, `tower-grpc` depends on the `connection-handshake` branch of `tower-h2`, but `tower-grpc-examples` depends on `master`; secondly, the code generated by `tower-grpc` depends on `http::PathAndQuery` having a `from_static` function, which was added in hyperium/hyper@4be1929e0c038bc575c24c38c1b1fadb7da48069 and isn't yet published to crates.io.
I've modified the `Cargo.toml`s for `tower-grpc` and `tower-grpc-examples` to resolve these issues.

Fix dependency conflicts in examples

---

src/client/mod.rs
src/generic/codec.rs
src/generic/server/streaming.rs

Fixes #12.
In 16c02a216a3f45779878c95dc492ae5e52bb0665, the client and server were refactored to share one generic `Encode` implementation. However, this resulted in client request streams ending in trailers when they weren't supposed to, breaking compatibility with other gRPC implementations (see https://github.com/tower-rs/tower-grpc/issues/12#issuecomment-354369747).
I added a boolean `return_trailers` field on `Encode`, which is now set `true` by servers and `false` by clients. 
Tested against `grpc-go` and `grpc-java`'s `helloworld` examples, and the issue described in #12 no longer occurs.

Encode only generates trailers on the server side

---

src/request.rs

I've added accessor functions to `Request` for getting the header map. I need to add headers to a request for [one of the gRPC interop test cases](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#cacheable_unary), and this seemed like the most ergonomic way to do it.

Add functions for accessing Request header map

---

Cargo.toml
tower-grpc-examples/Cargo.toml

A fresh clone generates the following errors:
```
$ cargo build
Updating git repository `http://github.com/hyperium/http`
Updating git repository `https://github.com/carllerche/codegen`             
Updating registry `https://github.com/rust-lang/crates.io-index`            
Updating git repository `https://github.com/tower-rs/tower`
Updating git repository `https://github.com/tower-rs/tower-h2`              
Updating git repository `https://github.com/carllerche/h2`                  
Updating git repository `https://github.com/carllerche/tokio-connect`       
Updating git repository `https://github.com/carllerche/string`              
Compiling libc v0.2.35                                                       
Compiling fnv v1.0.6
Compiling scoped-tls v0.1.0
Compiling cfg-if v0.1.2 …
```

Fix build errors with tower-h2 connection-handshake branch

---

Cargo.toml

This should fix compile errors against tower-rs/tower-h2@3c053d2d637e35f652e2533d27550d1d7065b107, caused by dependencies on different versions of `h2`.
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

Depend on h2 from crates.io

---

Cargo.toml
tests/multifile/Cargo.toml
tests/multifile/build.rs
tests/multifile/proto/hello.proto
tests/multifile/proto/world.proto
tests/multifile/src/lib.rs
tower-grpc-build/src/client.rs
tower-grpc-build/src/lib.rs

When `tower-grpc` is invoked on multiple `.proto` files, code generated for one file can make it into multiple output files. This is because the `ServiceGenerator` reuses the file root `codegen::Scope` even after it is `finalize()`ed.
I've changed `ServiceGenerator::finalize()` to replace the scope with a fresh one after outputting the generated code.
Fixes #31 
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

Zero codegen::Scope in ServiceGenerator::finalize

---

Cargo.toml
tests/collide/Cargo.toml
tests/collide/build.rs
tests/collide/proto/common.proto
tests/collide/proto/hello.proto
tests/collide/src/lib.rs
tower-grpc-build/src/client.rs
tower-grpc-build/src/lib.rs
tower-grpc-build/src/server.rs

Types from external proto files have their modules
imported and references are scoped by the imported
module.
Closes #33

Handle proto import collisions

---

src/client/mod.rs
src/codegen.rs
tower-grpc-build/src/client.rs
tower-grpc-examples/Cargo.toml
tower-grpc-examples/src/helloworld/client.rs
tower-grpc-examples/src/routeguide/client.rs
tower-grpc-interop/Cargo.toml
tower-grpc-interop/src/client.rs

Currently, the gRPC client sets the authority in the outbound HTTP
request. However, this is an HTTP/2.0 concern unrelated to gRPC. As
such, the HTTP service provided to the gRPC client should be responsible
for setting the origin.

Do not set the authority in the gRPC client.

---

.travis.yml
tower-grpc-build/src/client.rs
tower-grpc-build/src/lib.rs
tower-grpc-build/src/server.rs

It looks like the code added in PR #32 to fix the issue where `ServiceGenerator`s would output duplicate code when generating code for multiple .proto files (issue #31) was [accidentally removed](https://github.com/tower-rs/tower-grpc/commit/bbf1faca7e6e04aa611117e83d318dae44fc3835#diff-d15ac6177e75577c93c4041346f98ed0L125) in #44, creating a regression that caused issue #45.  
I've added this code back.
Furthermore, I was curious as to why the `test/multifile` test crate, which was added specifically to test for this bug, didn't catch this regression. It turns out that `test/multifile` does in fact fail to build on `master`, but we don't actually try to build it on Travis. Therefore, I also added a step to the CI build that tries to build the `test/multifile` and `test/collide` …

Zero codegen::Scope in ServiceGenerator::finalize, again 

---

Cargo.toml
src/codegen.rs
src/generic/server/mod.rs
src/generic/server/unary.rs
src/lib.rs

Primarily, `ReadyService` has been moved into a dedicated crate.
Depends on https://github.com/tower-rs/tower/pull/48.

Track Tower changes.

---

Cargo.toml
tower-grpc-examples/Cargo.toml
tower-grpc-interop/Cargo.toml

versions don't have to build both those versions and the older ones
that h2 is currently using.
Don't enable the regex support in env_logger. Applications that want
the regex support can enable it themselves; this will happen
automatically when they add their env_logger dependency.
Disable the env_logger dependency in quickcheck.
The result of this is that there are fewer dependencies. For example,
regex and its dependencies are no longer required at all, as can be
seen by observing the changes to the Cargo.lock. That said,
env_logger 0.5 does add more dependencies itself; however it seems
applications are going to use env_logger 0.5 anyway so this is still
a net gain.
Submitted on behalf of Buoyant, Inc.
Signed-off-by: Brian Smith <brian@briansmith.org>

Upgrade to env_logger 0.5 and log 0.4 so that projects that use those

---

src/client/client_streaming.rs
src/client/streaming.rs
src/codec.rs
src/error.rs
src/generic/codec.rs
src/generic/server/streaming.rs
src/lib.rs

It's often helpful for debugging and error handling to be able to distinguish between `Status::Unknown` from a server response and `Status::Unknown` due to something in the middle. Also, other header/trailer values are often useful for application logic.

Distinguish protocol errors from server errors

---

Cargo.toml
tests/unused-imports/Cargo.toml
tests/unused-imports/build.rs
tests/unused-imports/proto/bidi.proto
tests/unused-imports/proto/client_streaming.proto
tests/unused-imports/proto/hello.proto
tests/unused-imports/proto/server_streaming.proto
tests/unused-imports/src/lib.rs
tower-grpc-build/src/client.rs
tower-grpc-build/src/lib.rs
tower-grpc-build/src/server.rs

Fixes #56 
Previously, `tower-grpc-build`'s code generation for streaming RPCs may generate unused import statements, which cause the compiler to output a warning. This can occur in the generated server code's `methods` module for server-streaming RPCs, and in the generated client module for client-streaming RPCs, with the client code importing the method's request type and the server code importing the method's response type when. these types are not needed.
I've modified the generation of import statements to check if the RPC is streaming and skip the import of the appropriate type if so. Previously, imports were generated in a `for` loop that looped over the method's input and output types in a slice, in order to reduce repetition. This was no longer possible, as this change required …

Fix unused imports in generated code

---

Cargo.toml
src/generic/codec.rs

Usage of old `put_u32::<BigEndian>` / `get_u32::<BigEndian>` is deprecated in favor of `put_u32_be` / `get_u32_be`.
This generated compile error on latest on nightly

Fix deprecated usage of put_u32/get_u32

---

Cargo.toml
tests/collide/Cargo.toml
tests/multifile/Cargo.toml
tests/name-case/Cargo.toml
tests/unused-imports/Cargo.toml
tower-grpc-build/Cargo.toml
tower-grpc-examples/Cargo.toml
tower-grpc-interop/Cargo.toml

prost-0.4.0 has been released, which removes unnecessary dependencies
and has some protobuf-specific usability improvements.
See: https://github.com/danburkert/prost/releases/tag/v0.4.0

Update to prost-0.4.0

---

tower-grpc-interop/README.md
tower-grpc-interop/src/client.rs
tower-grpc-interop/travis-interop.sh

The reason the test was failing was simply that it was streaming the wrong Protobuf message.
Fixes #16.

Fix client_streaming interop test

---

src/codec.rs
src/generic/codec.rs
src/generic/server/streaming.rs

The associated constant `generic::codec::Codec::CONTENT_TYPE` is currently
unused and it's not clear how it can be used to set HTTP headers.
This change moves the constant to `generic::codec::Encoder::CONTENT_TYPE` and sets the header in server responses.

Set Content-Type for server responses

---

tower-grpc-examples/Cargo.toml
tower-grpc-examples/build.rs
tower-grpc-examples/proto/metadata/metadata.proto
tower-grpc-examples/src/metadata/client.rs
tower-grpc-examples/src/metadata/server.rs

In relation to #79. While it may be straightforward to some that gRPC metadata can directly be set as custom headers in the HTTP2 layer, it was not to me.
I think that adding it in the example may be useful to some until the `metadata` check box is ticked.

Adding custom metadata in helloworld client example

---

src/client/streaming.rs
src/error.rs
src/status.rs
tower-grpc-interop/Cargo.toml
tower-grpc-interop/README.md
tower-grpc-interop/src/client.rs
tower-grpc-interop/travis-interop.sh

The server_streaming test case is based on Eliza's work in #49.
When reviewing, please check if what I'm doing in `error.rs` is the idiomatic thing to do, I'm unsure. I could also do this without making the `Error` type implement `std::error::Error` but that would probably involve either messing around with refcounted assertion error lists or explicit stringing through of the errors, which would reduce readability. Another approach could be to refactor the tests to use a non-functional approach where assertions are side effectful.
I'm not sure how to best format the code for readability here. I added some non-mandatory type annotations in an attempt to make the code easier to follow, not sure what's the best practice is here
The code for this test case is really not that easy to read. …

Add interop test cases for streaming RPCs

---

Cargo.toml
src/body.rs
src/client/client_streaming.rs
src/client/mod.rs
src/client/server_streaming.rs
src/client/streaming.rs
src/client/unary.rs
src/codec.rs
src/codegen.rs
src/error.rs
src/generic/codec.rs
src/generic/server/grpc.rs
src/lib.rs
src/server/mod.rs
src/server/server_streaming.rs
src/server/unary.rs
src/status.rs
tower-grpc-build/Cargo.toml
tower-grpc-build/src/client.rs
tower-grpc-build/src/server.rs
tower-grpc-examples/Cargo.toml
tower-grpc-examples/src/helloworld/server.rs
tower-grpc-examples/src/metadata/server.rs
tower-grpc-examples/src/routeguide/server.rs
tower-grpc-interop/Cargo.toml
tower-grpc-interop/src/client.rs

- Uses `HttpService` from `tower-http`.
- Defines its own `Body` trait to be generic over.
- Adds a `tower-h2` feature to both `tower-grpc` and `tower-grpc-build`,
which if enabled, will provide impls for `tower-h2` types. This allows
the examples and interop to still work.

Remove required dependency on tower-h2

---

tower-grpc-build/src/server.rs

When I compile my code using `tower-grpc-build` with these rust 2018 attributes:
```rust
#![warn(rust_2018_compatibility)]
#![warn(rust_2018_idioms)]
```
it produces a warning about not explicitly using `dyn`.
```bash
warning: trait objects without an explicit `dyn` are deprecated
--> /Users/lucio/code/clique/target/debug/build/clique-a263e5c7d647a25f/out/clique.proto.rs:138:14
|
138 |             <tower::Service<http::Request<grpc::BoxBody>, Response=_, Error=_, Future=_>>::poll_ready(self)
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn tower::Service<http::Request<grpc::BoxBody>, Response=_, Error=_, Future=_>`
|
note: lint level defined here
--> src/lib.rs:6:9
|
6   | #![warn(rust_2018_idioms)]
|         ^^^^^^^^^^^^^^^^ …
```

Fix missing dyn in tower-grpc-build to satisfy rust 2018 idioms

---

src/lib.rs
src/metadata_key.rs
src/metadata_map.rs
src/metadata_value.rs
src/request.rs
tower-grpc-examples/src/metadata/client.rs
tower-grpc-examples/src/metadata/server.rs
tower-grpc-interop/src/client.rs

As per the discussion in #90, it wraps http::HeaderMap to abstract away the fact that tower-grpc is HTTP based. At this time this class is a pure wrapper that does not actually implement any of the gRPC metadata specific stuff (such as binary fields), that will come later.
My goal with this PR is to make `MetadataMap` (largely) equivalent to `HeaderMap` while not exposing http types.

Introduce tower_grpc::metadata::MetadataMap type

---

Cargo.toml
src/client/client_streaming.rs
src/client/streaming.rs
src/error.rs
src/generic/server/streaming.rs
src/lib.rs
src/status.rs
tower-grpc-interop/README.md
tower-grpc-interop/src/client.rs
tower-grpc-interop/travis-interop.sh

* Don't expose `HeaderMap` in the `Error` enum.
* Fix bug/typo that made the library give the status code in the error message field.
* Properly percent decode error messages, and add client interop test for it.

Some status code improvements

---

src/client/client_streaming.rs
src/codec.rs
src/error.rs
src/status.rs

Instead of providing a Prost specific type in the Error type, expose protobuf parse errors as INTERNAL errors, as speced in https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
This is kind of related to #90 but it's not quite that. I care about this because I think the `tower_grpc::Error` type should not exist (it should be replaced by `tower_grpc::Status`): The `Decode` variant is bad because it unnecessarily ties the library's public API to Prost, the `Inner` variant is bad because it forces users of this library to convert between separate tower_grpc `Error` types in ways that don't really make sense.
`Protocol` is not bad in itself, I just don't see when it can be useful: The only reason to expose an enum that is this detailed is if users of tower_grpc would write code that …

Remove one hard Prost dependency from tower-grpc's public interface

---

src/client/client_streaming.rs
src/error.rs
src/generic/codec.rs
src/lib.rs

This is the next step in my attempt to eliminate `tower_grpc::Error`, see #6.
After this, the only remaining thing is `tower_grpc::Error::Inner`, which is the trickiest one because `Inner` is kind of inherent to Tower's way of handling errors by wrapping error types in error types, see for example how [tower-timeout](https://github.com/tower-rs/tower/blob/master/tower-timeout/src/lib.rs#L26) does it.

Remove tower_grpc::ProtocolError

---

src/client/mod.rs
tower-grpc-build/src/client.rs

This change adds the ability to clone the outter client when the inner service is cloneable. This allows one to embed tower-buffer for example into the inner service to provide a cloneable and buffer backed client.
```rust
let say_hello = make_client.make_service(())
.map(move |conn| {
use hello_world::client::Greeter;
use tower_http::add_origin;
let conn = add_origin::Builder::new()
.uri(uri)
.build(conn)
.unwrap();
let conn = Buffer::new(conn, 100).unwrap();
Greeter::new(conn)
})
.and_then(|client| {
use hello_world::HelloRequest;
let mut client = client.clone();
client.say_hello(Request::new(HelloRequest {
name: "What is in a name?".to_string(),
})).map_err(|e| panic!("gRPC request failed; err={:?}", e))
})
```
This shoud also enable the ability to embed a client into a server for use …

Add clone impl for clients when the inner service impls clone

---

tower-grpc-interop/Cargo.toml

Several past versions of `untrusted`, a dependency of `rustls`,
were recently yanked from crates.io. This broke the version of 
`rustls` we previously depended on for the interop tests.
This branch updates the rustls version to one that depends on
a version of `untrusted` that was not yanked.

interop: bump rustls to 0.14.0 to make it compile

---

tower-grpc-build/src/client.rs
tower-grpc-build/src/lib.rs
tower-grpc-build/src/server.rs

grpc-build: generated code comments for methods, structs, and traits
Currently, the Rust code generated from protobuf files with comments
doesn't include the comments.
This branch fixes this by including the comments for
methods and structs on the client side and methods and traits on the
server side. This is done by calling doc on the sections of code that
generate new functions, structs, and traits. In the proto file, the
service comments are used for the structs and traits and the functions
comments inside those services are for the comments on methods. This
handles multiline comments that start immediately before functions
and services.
Fixes: #96

Retain protobuf comments

---

Cargo.toml
tests/uses_empty/Cargo.toml
tests/uses_empty/build.rs
tests/uses_empty/proto/uses_empty.proto
tests/uses_empty/src/lib.rs
tower-grpc-build/src/client.rs
tower-grpc-build/src/lib.rs
tower-grpc-build/src/server.rs

Currently, you need to manually make a type google::protobuf::Empty = ()

Support empty protos

---

tower-grpc-examples/Cargo.toml
tower-grpc-examples/src/helloworld/client.rs
tower-grpc-examples/src/metadata/client.rs
tower-grpc-examples/src/routeguide/client.rs

tower-rs/tower-h2@b9feae345a72396d82dc23d52a5a62689178bc40 broke the examples, these changes provide a fix.

Update the examples to MakeConnection change in tower-h2

---

README.md

We don't really need this line in the readme anymore, this library and tower is stable enough to support production use as showed by linkerd.

Remove the `do not use` disclaimer from the README

---

src/codegen.rs
src/generic/server/grpc.rs
src/generic/server/mod.rs
src/server/mod.rs
src/server/unimplemented.rs
src/status.rs
tower-grpc-build/src/server.rs
tower-grpc-interop/Cargo.toml
tower-grpc-interop/build.rs
tower-grpc-interop/src/client.rs
tower-grpc-interop/src/server.rs
tower-grpc-interop/travis-interop.sh

Previously, since the generated error body would yield `true` for
`is_end_stream`, the `grpc-status` would never be sent in the trailers.
This adds some basic server interop tests which would see this bug.

Fix server's generated unimplemented catch-all

---

src/codegen.rs
tower-grpc-build/src/client.rs
tower-grpc-interop/src/client.rs

Generate type-safe bounds for Client Streaming RPCs

---

src/codegen.rs
src/error.rs
src/generic/server/client_streaming.rs
src/generic/server/server_streaming.rs
src/generic/server/streaming.rs
src/generic/server/unary.rs
src/server/client_streaming.rs
src/server/server_streaming.rs
src/server/streaming.rs
src/server/unary.rs
src/server/unimplemented.rs
tower-grpc-build/src/server.rs

I noticed that the generated and internal server `Future`s claim an error type of `h2::Error`, but they don't ever return an error (any error is instead turned into a `Response` with an appropriate `grpc-status`). This does two things:
- Reduces the coupling to `h2::Error`
- More properly conveys that these futures cannot error

Replace server future's errors with Never

---

tower-grpc-examples/src/helloworld/client.rs
tower-grpc-examples/src/metadata/client.rs

The server is listening on an ipv6 address, so the client should also connect on an ipv6 address.

Client should use ipv6 for connecting to server

---

Cargo.toml
src/codegen.rs
src/lib.rs
tower-grpc-examples/Cargo.toml
tower-grpc-examples/src/helloworld/client.rs
tower-grpc-examples/src/metadata/client.rs
tower-grpc-examples/src/routeguide/client.rs

`MakeService` was moved into `tower-util`; so tower-grpc needs to use the updated dependency.

Replace tower dependency with tower-util

---

tower-grpc-examples/Cargo.toml
tower-grpc-examples/src/helloworld/client.rs
tower-grpc-examples/src/metadata/client.rs
tower-grpc-examples/src/routeguide/client.rs
tower-grpc-interop/Cargo.toml
tower-grpc-interop/src/client.rs

Switch from `tower-add-origin` to `tower-request-modifier`. I was hoping this would serve as a clean minimal representation of a trait issue I'm having elsewhere, but it ended up being an easy conversion.

Use tower-request-modifier

---

tower-grpc-interop/Dockerfile-client-tower
tower-grpc-interop/docker-compose.yml
tower-grpc-interop/src/client.rs
tower-grpc-interop/travis-interop.sh

Issue: #27 
Some issues I encountered
- Test server returns no binary metadata. This may be due to the fact that trailing metadata are not fully supported as mentioned in #90 
- No metadata returned for duplex calls at all

Added custom_metadata interop test

---

tower-grpc-examples/Cargo.toml
tower-grpc/Cargo.toml

Now when tower/tower has been published to crates.io (which is great!), if one was using tower-grpc one would get the git version of tower-util in addition to v0.1 from crates.io if one was using tower in general.
So here is an upgrade of tower-util to v0.1 from crates.io instead of the old git dependency.

Use published tower-util 0.1 instead of from git

---

tower-grpc/Cargo.toml
tower-grpc/src/body.rs
tower-grpc/src/codegen.rs
tower-grpc/src/lib.rs

This also brings us a step closer to releasing by removing another git dep for its published version.

Remove tower-http infavor of http-body

---

tests/multifile/Cargo.toml
tests/multifile/src/lib.rs
tests/name-case/Cargo.toml
tests/name-case/src/lib.rs
tests/unused-imports/Cargo.toml
tests/unused-imports/src/lib.rs
tests/uses_empty/Cargo.toml
tower-grpc-build/Cargo.toml
tower-grpc-build/src/server.rs
tower-grpc-interop/Cargo.toml
tower-grpc-interop/Dockerfile-server-go
tower-grpc-interop/src/client.rs
tower-grpc-interop/src/server.rs
tower-grpc-interop/travis-interop.sh
tower-grpc/Cargo.toml
tower-grpc/src/codegen.rs
tower-grpc/src/lib.rs

This removes all traces of tower-h2 from all the crates. This should get us one step closer to a release!

Remove tower-h2 in favor of tower-hyper in tests

---

tower-grpc-examples/build.rs

As the examples are going to be cribbed by application developers, it's important to demonstrate how rebuilds using tower-grpc-build can be reduced by printing `cargo:rerun-if-changed` instructions for cargo to only rerun the build script if the .proto files change.

Show usage of cargo:rerun-if-changed in examples
